import React from 'react';

const strings={
    en:{
        sermon:'SERMON',
        ministry:'MINISTRY',
        about:'ABOUT',
        photo:'PHOTO',
        language:'한국어',
        sundaySermon:'SERMON',
        ministryTeam:'MINISTRY TEAM',
        kids:'KIDS',
        youth:'YOUTH',
        youngAdult:'YOUNG ADULT',
        link:'LINK',
        aboutChurch:'ABOUT CHURCH',
        historyAndVision:'HISTORY & VISION',
        aboutPastorPaul:'ABOUT PASTOR PAUL',
        timeAndLocation:'TIME & LOCATION',
        pastors:'PASTORS',
        ordainedDecon:'ORDAINED DECON',
        cellGroup:'CELL GROUP',
        news2020:'2020 NEWS',
        photoGallary:'PHOTO GALLARY',
        title:'TITLE',
        date:'DATE',
        serviceInfo:'SERVICE INFO',
        sun1:'SUNDAY 1',
        sun2:'SUNDAY 2',
        earlyMorningPrayer:'EARLY MORNING PRAYER',
        tueToFri:'TUE-FRI',
        tuesday:'TUESDAY',
        wednesday:'WEDNESDAY',
        friday:'FRIDAY',
        usefulLinks:'USEFUL LINKS',
        contact:'CONTACT',
        adminLogin:'ADMIN LOGIN',
        duranno:'DURANNO',
        christiantimes:'CHRISTIAN TIMES',
        godpeople:'GOD PEOPLE',
    },
    kr:{
        sermon:'설교영상',
        ministry:'사역',
        about:'교회소개',
        photo:'사진',
        language:'ENGLISH',
        sundaySermon:'주일설교',
        ministryTeam:'부서 및 전문사역',
        kids:'어린이부',
        youth:'청소년부',
        youngAdult:'청년부',
        link:'바로가기',
        aboutChurch:'교회소개',
        historyAndVision:'교회역사 및 비전',
        aboutPastorPaul:'담임목사소개',
        timeAndLocation:'예배시간 및 오시는길',
        pastors:'교역자소개',
        ordainedDecon:'섬기는사람들',
        cellGroup:'구역모임',
        news2020:'2020년 교회주보',
        photoGallary:'포토갤러리',
        title:'제목',
        date:'작성일',
        serviceInfo:'예배 안내',
        sun1:'주일1부',
        sun2:'주일2부',
        earlyMorningPrayer:'새벽기도회',
        tueToFri:'화~금',
        tuesday:'화요중보기도',
        wednesday:'수요예배',
        friday:'금요기도회',
        usefulLinks:'유용한 사이트',
        contact:'연락처',
        adminLogin:'관리자 로그인',
        duranno:'생명의삶',
        christiantimes:'크리스천신문',
        godpeople:'갓피플',
    }
}

export default strings;